# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatiRaccolti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('erogation', models.BooleanField(default=False)),
            ],
        ),
    ]
