# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dispenser', '0003_auto_20190812_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datiraccolti',
            old_name='created_on',
            new_name='date',
        ),
    ]
